import re
from typing import Tuple
from jose import jwt, JWTError
from fastapi import HTTPException, Security
from fastapi.security import APIKeyHeader
from ai.core.config import settings
from ai.core.logging import logger

api_key_header = APIKeyHeader(name=settings.API_KEY_HEADER, auto_error=False)

# List of common prompt injection patterns
INJECTION_KEYWORDS = [
    r"ignore\s+previous\s+instructions",
    r"system\s+override",
    r"you\s+are\s+now\s+a\s+jailbroken",
    r"do\s+anything\s+now",
    r"dan\s+mode",
    r"ignore\s+system\s+prompt",
    r"bypass\s+restrictions",
    r"forget\s+what\s+I\s+said\s+before"
]

def check_prompt_injection(prompt: str) -> Tuple[bool, str]:
    """
    Checks if a given prompt text matches known prompt injection signatures.
    Returns: (is_injected, explanation)
    """
    if not prompt:
        return False, ""
        
    normalized = prompt.lower()
    for pattern in INJECTION_KEYWORDS:
        if re.search(pattern, normalized):
            logger.warning(f"Prompt injection pattern detected: '{pattern}'")
            return True, f"Security Violation: Input matched injection signature: '{pattern}'"
            
    return False, ""

def verify_jwt_token(token: str) -> dict:
    """
    Decodes and validates a JWT token generated by the BuildSpace backend.
    """
    try:
        payload = jwt.decode(
            token,
            settings.JWT_SECRET,
            algorithms=[settings.JWT_ALGORITHM]
        )
        return payload
    except JWTError as e:
        logger.error(f"JWT decode error: {e}")
        raise HTTPException(
            status_code=401,
            detail="Could not validate credentials. Invalid or expired token."
        )

def verify_api_key(api_key: str = Security(api_key_header)) -> str:
    """
    Validates API key for external service integrations.
    """
    if api_key == settings.ADMIN_API_KEY:
        return api_key
    raise HTTPException(
        status_code=403,
        detail="Could not validate API Key."
    )
